apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: "arn:aws:iam::<AWS-ACCOUNT-ID>:role/<ROLE-NAME>" ## Put here the Role name created by Terraform in modules/eks-workers/iam.tf
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes